### ISSUE TITLE
Only works 1x for *.h file(s)

### ISSUE THREAD

**Issue by Skrell** [Ekopalypse/EnhanceAnyLexer#10]
In pic attached you can see that I'm trying to highlight the term "Q_PROPERTY" in this C/C++ *.h file...  The green colorization works when I type it into the EnhanceAnyLexerConfig.ini, but as soon as I click on the file itself in notepad++ the color disappears (even if I reload it) 

![image](https://github.com/Ekopalypse/EnhanceAnyLexer/assets/590266/a67ff515-3b10-40f9-8d87-5e38958c2e3d)

![image](https://github.com/Ekopalypse/EnhanceAnyLexer/assets/590266/481219cd-93df-45ac-8c64-44650120c5a7)

**Comment by Ekopalypse** [comment]
It looks like you are using the exclude_styles for UDLs and not the ones for C++.
If you check your <whatever_theme>.xml, you should see that c++ uses style_id 11 as the default (identifier) style. See [here](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/4ba92b04ec01132978365a79c4898c8f3285b088/lexilla/include/SciLexer.h#L299) for scintilla reference.
So, if you use something like `excluded_styles = 1,2,3,4,5,6,7,9,10,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27`
it should work.

**Comment by Skrell** [comment]
My apologies yes it works!  I guess after reading the documentation I don't really understand what "excluded_styles" is for?

**Comment by Skrell** [comment]
Also can you please change the format to 0xRGB instead of 0xBGR
From your document:
; * red goes in the lowest byte (0x0000FF)
; * green goes in the center byte (0x00FF00)
; * blue goes in the biggest byte (0xFF0000)

**Comment by Ekopalypse** [comment]
> ... what "excluded_styles" is for?

All lexers use so-called StyleIDs to assign color and font attributes to the individual lexical tokens. EnhanceAnyLexer would, if you don't define excluded_styles, overwrite matches in these areas as well which is not desired under normal circumstances. Unfortunately there is, also understandably, no standard that defines which ID is assigned to which token type and what I personally see even more critical, lexers treat identifiers in different languages differently. Some ignore them and automatically use the default foreground color, others, like the Cpp lexer, explicitly assign an ID (in this case 11). I'm wondering if there is a way to inform users that there are matches that are in areas that are already colored by the lexer they are using, to make them aware of this.

> ... can you please change the format

I can't really do that, because that would mean that 
1. all existing solutions would be affected after an update and
2. the plugin would have to convert this again as this is the expected format (from Scintilla and Microsoft).

**Comment by Ekopalypse** [comment]
I'm thinking about something like this to inform users that matches may not be showing.

![image](https://github.com/Ekopalypse/EnhanceAnyLexer/assets/47723516/e5ff6291-b64a-4e6f-860c-027ab666a957)

**Comment by Skrell** [comment]
> > ... what "excluded_styles" is for?
> 
> All lexers use so-called StyleIDs to assign color and font attributes to the individual lexical tokens. EnhanceAnyLexer would, if you don't define excluded_styles, overwrite matches in these areas as well which is not desired under normal circumstances. Unfortunately there is, also understandably, no standard that defines which ID is assigned to which token type and what I personally see even more critical, lexers treat identifiers in different languages differently. Some ignore them and automatically use the default foreground color, others, like the Cpp lexer, explicitly assign an ID (in this case 11). I'm wondering if there is a way to inform users that there are matches that are in areas that are already colored by the lexer they are using, to make them aware of this.
> 
> > ... can you please change the format
> 
> I can't really do that, because that would mean that
> 
> 1. all existing solutions would be affected after an update and
> 2. the plugin would have to convert this again as this is the expected format (from Scintilla and Microsoft).

What about a switch for new users such as myself that can be enabled to change to RGB?   I believe RGB is how the actual colors are stored for each style's bgColor and fgColor so I really think this is more natural for theme makers.

**Comment by Ekopalypse** [comment]
> What about a switch for new users such as myself that can be enabled to change to RGB?

Added with  version [v.1.4.0](https://github.com/Ekopalypse/EnhanceAnyLexer/releases/tag/v.1.4.0), which is currently marked as pre-release for a test period of 1 week.

**Comment by Skrell** [comment]
Just tested it and it works great!  Now I can easily copy and paste color codes from the notepad++ themes and use them to add additional keywords with your regular expressions!

**Comment by Ekopalypse** [comment]
Thank you for testing as well and letting me know. 
I will close this, but if you or I or whoever finds something that doesn't work with this change, the issue can of course be reopened.
